logstash_version: 2.1
logstash_defaults: |
        LS_USER=root
        LS_GROUP=root
        LS_HEAP_SIZE="256m"

logstash_inputs: |
 kafka{
    zk_connect => "10.0.2.2:2181"
    topic_id => "test"
    codec => "json"
    type => "json"
    }
logstash_filters: |

logstash_outputs: |
 file {
    path => "/var/log/logstash/output.log"
    }
 elasticsearch {
    document_type => "example"
    hosts => "127.0.0.1"
  }

